# Generated by Django 6.0.6 on 2026-06-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_product_category_order_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
